deepinsight:
  # build: .
  image: "sangseoklim/deepinsight:latest"
  ports:
   - "49160:3000"
   - "49161:9229"
  environment:
    ENV: DEV
  # logging:
  #   driver: "fluentd"
  #   options:
  #     fluentd-address: localhost:24224
  #     tag: httpd.access