fluentd:
  image: "sangseoklim/fluentd:latest"
  ports:
   - "24224:24224"
   - "24224:24224/udp"
  volumes:
   - /data/fluentd/log:/fluentd/log
   - /data/fluentd/conf:/fluentd/etc
  environment:
   - FLUENTD_CONF=fluent.conf
  links:
    - "elasticsearch"
elasticsearch:
  image: elasticsearch
  expose:
    - 9200
  ports:
    - "9200:9200"
kibana:
  image: kibana
  links:
    - "elasticsearch"
  ports:
    - "5601:5601"
