fluentd:
  image: "fluent/fluentd:latest"
  ports:
   - "24224:24224"
   - "24224:24224/udp"
  volumes:
   - /data/fluentd:/fluentd/log
elasticsearch:
  image: elasticsearch
  expose:
    - 9200
  ports:
    - "9200:9200"
kibana:
  image: kibana
  links:
    - "elasticsearch"
  ports:
    - "5601:5601"